config/routes.rb
Rails.application.routes.draw do
  root 'groups#index'
  devise_for :users
  resources :users, only: [:edit, :update, :destroy, :index]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :users, through: :members
  has_many :members
  has_many :messages

  def show_last_message
    if (last_message = messages.last).present?
      last_message.text? ? last_message.text : "Image submitted"
    else
      "No message yet"
    end
  end
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :text, presence: true, unless: :image?

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :groups, through: :members
  has_many :members
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
 

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  protected

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    if user_signed_in?
      @users_group = current_user.groups
    else
      redirect_to new_user_session_path
    end
  end

  def new
    @group = current_user.groups.new
  end

  def create
    add_current_user
    @group = Group.new(group_params)
    if @group.save
      flash[:notice] = "グループを作成しました"
      redirect_to action: :index
    else
      render "new"
    end
  end

  def show
    @users_group = current_user.groups
    redirect_to controller: "messages", action: "index"
  end

  def edit
    @group = current_user.groups.find(params[:id])
  end

  def update
    add_current_user
    @group = current_user.groups.find(params[:id])
    if @group.update group_params
      flash[:notice] = "グループを更新しました"
      redirect_to action: :index
    else
      render "edit"
    end
  end

  def add_current_user
    if params[:group][:user_ids] == nil 
      params[:group][:user_ids] = [current_user.id.to_s]
    else 
      params[:group][:user_ids].push(current_user.id.to_s)
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :find_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
    respond_to do |format|
      format.html
      format.json { @new_message = @messages.where('id > ?', params[:id]) }
    end
  end

  def create
    @message = @group.messages.new(input_params)
    if @message.save
      respond_to do |format|
        format.html {redirect_to group_messages_path(@group)}
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = "Message is blank"
      render "index"
    end
  end

  private

  def find_group
    @group = Group.find(params[:group_id])
    @users_group = current_user.groups
    gon.group = @group[:id]
  end

  def input_params
    params.require(:message).permit(:text, :image).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where('name Like ? AND id != ?', "%#{params[:keyword]}%", current_user.id).limit(7)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit
  end

  def update
    user = User.find(params[:id])
      if user.id == current_user.id
        user.update(user_params)
        redirect_to root_path
      end
  end

  def destroy
    flash[:alert] = "You need to login"
    user = User.find(params[:id])
    sign_out user
    redirect_to new_user_session_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_group.html.haml
.groups
  - @users_group.each do |i|
    .group
      = link_to group_messages_path(current_user.groups.find_by(name: i.name)) do
        -# link to chatroom will be changed in the future
        .group__name
          = i.name
        .group__message
          = i.show_last_message
        -# group__name & __message will be dynamically generated

app/views/groups/_sidebar.html.haml
.sidebar
  .header
    %h3{class: "header__name"} Username
    -# username will be dynamically generated
    %ul{class: "header__list"}
      %li{class: "list"}
        = link_to new_group_path, data: { turbolinks: 'false'} do
          -# replace button links in the future
          %i{class: "fa fa-pencil-square-o icon"}
      %li{class: "list"}
        = link_to edit_user_path(current_user) do
          %i{class: "fa fa-cog icon"}
  = render partial: "groups/group"

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = form_for @group, html: {class: "edit_chat_group", id: "edit_chat_group_22"} do |f|
    - if @group.errors.any?
      .chat-group-form__errors
        - @group.errors.messages.each do |attr, message|
          - message.each do |val|
            %h2 1件のエラーが発生しました。
            %ul
              %li= val
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :chat_group_name, "グループ名", class: "chat-group-form__label"
      .chat-group-form__field--right
        = f.text_field :name, placeholder: "グループ名を入力してください", class: "chat-group-form__input", id: "chat_group_name"
    .chat-group-form__field.clearfix
      = render template: "users/index"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :member, "チャットメンバー", class: "chat-group-form__label"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = render "users/list"
        = f.submit "更新する", data: {disable_with: "Save"}, class: "chat-group-form__action-btn"

app/views/groups/index.html.haml
!!!
%html
  %head
  -# .notification
  .wrapper
    = render "groups/sidebar"
  %body

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = form_for @group, html: {class: "new_chat_group", id: "new_chat_group"} do |f|
    - if @group.errors.any?
      .chat-group-form__errors
        - @group.errors.messages.each do |attr, message|
          - message.each do |val|
            %h2 1件のエラーが発生しました。
            %ul
              %li= val
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, "グループ名", class: "chat-group-form__label"
      .chat-group-form__field--right
        = f.text_field :name, placeholder: "グループ名を入力してください", class: "chat-group-form__input", id: "chat_group_name"
    .chat-group-form__field.clearfix
      = render template: "users/index"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :member, "チャットメンバー", class: "chat-group-form__label"
      .chat-group-form__field--right
        = render "users/list"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit "登録", data: {disable_with: "Save"}, class: "chat-group-form__action-btn"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    = Gon::Base.render_data
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - flash.each do |key, value|
      = content_tag(:div, value, class: "flash flash__#{key}")
    = yield

app/views/messages/_chat.html.haml
.chat
  .header
    .left-header
      .left-header__title
        = @group.name
      %ul{class: "left-header__members"}
        Members:
        - @group.users.each do |i|
          %li{class: "member"}
            = i[:name]
    .right-header
      = link_to edit_group_path(@group), class: "right-header__button", data: { turbolinks: 'false'} do
        Edit
  = render "message"
  = render "input"

app/views/messages/_input.html.haml
.form
  = form_for [@group, @message] do |f|
    = f.text_field :text, class: "form__message", placeholder: "Hue hue hue he he he"
    .form__mask
      = f.label :image, class: "form__mask__image" do
        = fa_icon "picture-o", class: "icon"
        = f.file_field :image, class: "hidden"
    = f.submit "Send", class: "form__submit"

app/views/messages/_message.html.haml
.messages
  - @messages.each do |message|
    .message{data: {id: message.id}}
      .upper-message
        .upper-message__username
          = message.user.name
        .upper-message__date
          = message.created_at.to_s[0..15]
      .lower-message
        %p{class:"lower-message__content"}
          = message.text
          = image_tag message.image

app/views/messages/_sidebar.html.haml
.sidebar
  .header
    %h3{class: "header__name"} Username
    -# username will be dynamically generated
    %ul{class: "header__list"}
      %li{class: "list"}
        %a{href: "http://www.mozilla.com/en-US/firefox/" }
          -# replace button links in the future
          %i{class: "fa fa-pencil-square-o icon"}
      %li{class: "list"}
        %a{href: "http://www.mozilla.com/en-US/firefox/" }
          -# replace button links in the future
          %i{class: "fa fa-cog icon"}
  = render "group"

app/views/messages/index.html.haml
!!!
%html
  %head
  -# .notification
  .wrapper
    = render template: "groups/index"
    = render "chat"
  %body

app/views/users/_list.html.haml
#chat-group-users
  - @group.users.where.not(id: current_user.id).each do |f|
    .chat-group-user.clearfix.js-chat-member
      %input{name: "group[user_ids][]", type: "hidden", value: f.id}
      %p.chat-group-user__name #{f[:name]}
      %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn 削除

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", user_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'

app/views/users/index.html.haml
.chat-group-form__field--left
  = label :members, "チャットメンバーを追加", class: "chat-group-form__label"
.chat-group-form__field--right
  .chat-group-form__search.clearfix
    = text_field :chat, :members, id: "user-search-field", class: "chat-group-form__input", placeholder: "追加したいユーザー名を入力してください"
  #user-search-result